/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.modelo.Asunto;
import ec.edu.ups.modelo.Persona;
import ec.edu.ups.modelo.Procurador;
import java.sql.Date;
import java.time.ZoneId;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul Idrovo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCliente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnCliente = new javax.swing.JButton();
        pnlProcurador = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccion2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono2 = new javax.swing.JTextField();
        btnProcurador = new javax.swing.JButton();
        btnNuevoAsunto = new javax.swing.JButton();
        txtNumeroExpediente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAsunto = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCliente = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstProcurador = new javax.swing.JList<>();
        dtFechaFinalizacion = new com.toedter.calendar.JDateChooser();
        dtFechaIngreso = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtTipoExpediente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnListarAsunto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel9.setText("CEDULA");

        txtCedula.setEnabled(false);
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        jLabel12.setText("NOMBRE");

        txtNombre.setEnabled(false);

        jLabel13.setText("DIRECCION");

        txtDireccion.setEnabled(false);

        jLabel14.setText("TELEFONO");

        txtTelefono.setEnabled(false);

        btnCliente.setText("ASIGNAR");
        btnCliente.setEnabled(false);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(60, 60, 60))
                            .addGroup(pnlClienteLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(55, 55, 55)))
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnCliente)))
                .addContainerGap())
            .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlClienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel9))
                    .addGap(70, 70, 70)
                    .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlClienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        pnlProcurador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROCURADOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel7.setText("CEDULA");

        txtCedula2.setEnabled(false);
        txtCedula2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedula2KeyTyped(evt);
            }
        });

        jLabel8.setText("NOMBRE");

        txtNombre2.setEnabled(false);

        jLabel10.setText("DIRECCION");

        txtDireccion2.setEnabled(false);

        jLabel11.setText("TELEFONO");

        txtTelefono2.setEnabled(false);

        btnProcurador.setText("ASIGNAR");
        btnProcurador.setEnabled(false);
        btnProcurador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcuradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProcuradorLayout = new javax.swing.GroupLayout(pnlProcurador);
        pnlProcurador.setLayout(pnlProcuradorLayout);
        pnlProcuradorLayout.setHorizontalGroup(
            pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcuradorLayout.createSequentialGroup()
                .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProcuradorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProcuradorLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(60, 60, 60))
                            .addGroup(pnlProcuradorLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(55, 55, 55)))
                        .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion2)
                            .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlProcuradorLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnProcurador)))
                .addContainerGap())
            .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlProcuradorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7))
                    .addGap(70, 70, 70)
                    .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombre2)
                        .addComponent(txtCedula2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        pnlProcuradorLayout.setVerticalGroup(
            pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProcuradorLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnProcurador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlProcuradorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(pnlProcuradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        btnNuevoAsunto.setText("NUEVO ASUNTO");
        btnNuevoAsunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAsuntoActionPerformed(evt);
            }
        });

        txtNumeroExpediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroExpedienteKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Numero Expediente");

        lstAsunto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ASUNTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N
        lstAsunto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAsunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAsuntoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstAsunto);

        lstCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N
        lstCliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstCliente);

        lstProcurador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROCURADORES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N
        lstProcurador.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lstProcurador);

        dtFechaFinalizacion.setDateFormatString("dd-MM-yyyy");

        dtFechaIngreso.setDateFormatString("dd-MM-yyyy");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Estado Expediente");

        txtTipoExpediente.setEnabled(false);
        txtTipoExpediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoExpedienteKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Fecha Ingreso");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Fecha Finalizacion");

        btnListarAsunto.setText("LISTAR ASUNTOS");
        btnListarAsunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAsuntoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(pnlProcurador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnListarAsunto)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(117, 117, 117)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(115, 115, 115)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTipoExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtFechaFinalizacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addComponent(btnNuevoAsunto)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(dtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNumeroExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTipoExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dtFechaFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnNuevoAsunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlProcurador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnListarAsunto)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char validar = evt.getKeyChar();
        int asscii = (int) validar;
        if (!Character.isDigit(validar) && validar != '\n' && asscii != 8 && validar != '') {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INGRESE SOLO NUMEROS", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
        if (validar == '\n') {
            Persona p = new Persona();
            p = p.obtenerPersonaCedula(txtCedula.getText());
            if (p != null) {
                txtNombre.setText(p.getNombre());
                txtDireccion.setText(p.getDireccion());
                txtTelefono.setText(p.getTelefono());
            } else {
                JOptionPane.showMessageDialog(null, "PERSONA NO REGISTRADA. PROCEDA A AGREGARLA", "INFORMACION", 1);
                CrearPersona crearPersona = new CrearPersona(this);
                crearPersona.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCedula2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedula2KeyTyped
        char validar = evt.getKeyChar();
        int asscii = (int) validar;
        if (!Character.isDigit(validar) && validar != '\n' && asscii != 8 && validar != '') {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INGRESE SOLO NUMEROS", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
        if (validar == '\n') {
            Persona p = new Persona();
            p = p.obtenerPersonaCedula(txtCedula2.getText());
            if (p != null) {
                txtNombre2.setText(p.getNombre());
                txtDireccion2.setText(p.getDireccion());
                txtTelefono2.setText(p.getTelefono());
            } else {
                JOptionPane.showMessageDialog(null, "PERSONA NO REGISTRADA. PROCEDA A AGREGARLA", "INFORMACION", 1);
                CrearPersona crearPersona = new CrearPersona(this);
                crearPersona.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtCedula2KeyTyped

    private void txtNumeroExpedienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroExpedienteKeyTyped
        char validar = evt.getKeyChar();
        int asscii = (int) validar;
        if (!Character.isDigit(validar) && validar != '\n' && asscii != 8 && validar != '') {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INGRESE SOLO NUMEROS", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
        if (validar == '\n') {
            if (!txtNumeroExpediente.getText().equals("")) {
                txtCedula.setEnabled(true);
                txtCedula2.setEnabled(true);
                txtTipoExpediente.setEnabled(true);
                btnCliente.setEnabled(true);
                btnProcurador.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "CAMPO VACIO", "INFORMACION", 1);
            }
        }
    }//GEN-LAST:event_txtNumeroExpedienteKeyTyped

    private void txtTipoExpedienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoExpedienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoExpedienteKeyTyped

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        boolean repetido = false;
        if (lstProcurador.getModel().getSize() != 0) {
            DefaultListModel<String> modeloLista2 = (DefaultListModel<String>) lstProcurador.getModel();
            for (int i = 0; i < modeloLista2.getSize(); i++) {
                if (modeloLista2.getElementAt(i).equals(txtCedula.getText())) {
                    repetido = true;
                    break;
                }
            }
        }
        if (!repetido) {
            modeloLista.addElement(txtCedula.getText());
            lstCliente.setModel(modeloLista);
            txtCedula.setEnabled(false);
            btnCliente.setEnabled(false);
            txtCedula.setText("");
            txtNombre.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "ESTA CEDULA YA ESTA ASIGNADA COMO PROCURADOR", "INFORMACION", 1);
        }
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProcuradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcuradorActionPerformed
        DefaultListModel<String> modeloLista;
        if (lstProcurador.getModel().getSize() == 0) {
            modeloLista = new DefaultListModel<>();
        } else {
            modeloLista = (DefaultListModel<String>) lstProcurador.getModel();
        }
        boolean repetido = false;
        for (int i = 0; i < modeloLista.getSize(); i++) {
            if (modeloLista.getElementAt(i).equals(txtCedula2.getText())) {
                repetido = true;
                break;
            }
        }
        if (!repetido) {
            modeloLista.addElement(txtCedula2.getText());
            lstProcurador.setModel(modeloLista);
            txtCedula2.setText("");
            txtNombre2.setText("");
            txtDireccion2.setText("");
            txtTelefono2.setText("");
        }
    }//GEN-LAST:event_btnProcuradorActionPerformed

    private void btnNuevoAsuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAsuntoActionPerformed
        boolean fechas = verificadorFechas();
        if (!txtNumeroExpediente.getText().equals("") && fechas && !txtTipoExpediente.getText().equals("") && lstCliente.getModel().getSize() != 0 && lstProcurador.getModel().getSize() != 0) {
            java.util.Date fechaIngreso = dtFechaIngreso.getDate();
            Date fechaSqlIngreso = Date.valueOf(fechaIngreso.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            java.util.Date fechaFinalizacion = dtFechaIngreso.getDate();
            Date fechaSqlFinalizacion = Date.valueOf(fechaFinalizacion.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            Asunto as = new Asunto();
            as.setNumeroExpediente(txtNumeroExpediente.getText());
            as.setEstado(txtTipoExpediente.getText());
            as.setFechaInicio(fechaSqlIngreso);
            as.setFechaFinal(fechaSqlFinalizacion);
            as.setCedula(lstCliente.getModel().getElementAt(0));
            boolean creacion = as.crearAsunto(as);
            if (creacion) {
                DefaultListModel<String> modeloLista = (DefaultListModel<String>) lstProcurador.getModel();
                for (int i = 0; i < modeloLista.size(); i++) {
                    Procurador pr = new Procurador(txtNumeroExpediente.getText(), modeloLista.getElementAt(i));
                    pr.crearProcurador(pr);
                }                
                txtNumeroExpediente.setText("");
                txtTipoExpediente.setText("");
                txtCedula.setText("");
                txtCedula2.setText("");
                lstCliente.setModel(new DefaultListModel<>());
                lstProcurador.setModel(new DefaultListModel<>());
            }
        } else {
            JOptionPane.showMessageDialog(null, "FALTAN DATOS", "INFORMACION", 1);
        }
    }//GEN-LAST:event_btnNuevoAsuntoActionPerformed

    private void btnListarAsuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAsuntoActionPerformed
        List<Asunto> listaAsuntos = new Asunto().obtenerListaAsuntos();
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        for (Asunto listaAsunto : listaAsuntos) {
            modeloLista.addElement(listaAsunto.getNumeroExpediente());
        }
        lstAsunto.setModel(modeloLista);
        
    }//GEN-LAST:event_btnListarAsuntoActionPerformed

    private void lstAsuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAsuntoMouseClicked
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        String numeroExpediente = new Asunto().obtenerClienteCedula(lstAsunto.getSelectedValue());
        modeloLista.addElement(numeroExpediente);
        lstCliente.setModel(modeloLista);
        modeloLista = new DefaultListModel<>();
        List<Procurador> listaProcurador = new Procurador().obtenerListaProcuradorAsuntoId(lstAsunto.getSelectedValue());
        for (Procurador procurador : listaProcurador) {
            modeloLista.addElement(procurador.getCedula());
        }        
        lstProcurador.setModel(modeloLista);
    }//GEN-LAST:event_lstAsuntoMouseClicked
    
    private boolean verificadorFechas() {
        try {
            java.util.Date fechaIngreso = dtFechaIngreso.getDate();
            java.util.Date fechaFinalizacion = dtFechaIngreso.getDate();
            return true;
        } catch (Exception e) {
            return false;
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnListarAsunto;
    private javax.swing.JButton btnNuevoAsunto;
    private javax.swing.JButton btnProcurador;
    private com.toedter.calendar.JDateChooser dtFechaFinalizacion;
    private com.toedter.calendar.JDateChooser dtFechaIngreso;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstAsunto;
    private javax.swing.JList<String> lstCliente;
    private javax.swing.JList<String> lstProcurador;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlProcurador;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedula2;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNumeroExpediente;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono2;
    private javax.swing.JTextField txtTipoExpediente;
    // End of variables declaration//GEN-END:variables
}
